apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deploy-autosceling
  labels:
     app: my-k8s-application
spec:
  replicas: 2
  selector:
    matchLabels:
      project: mossa
  template:
    metadata:
      labels:
        project: mossa
    spec:
      containers:
        - name : mossa-web
          image: adv4000/k8sphp:version1
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: my-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: my-web-deploy-autosceling
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
     name: cpu
     target:
      type: Utilization
      averageUtilization: 70
  - type: Resource
    resource:
     name: memory
     target:
      type: Utilization
      averageUtilization: 80
